title: "Marisara Satrulee"
logo: "/assets/img/Prof_img.jpg"
description: |
  I recently graduated in 2024 with a Master of Data Science from the University of Technology Sydney (UTS) in Australia. 
  Prior to my master's degree, I gained 10 years of experience in sales, marketing, and content creation from companies in the retail and education sectors. 
  While studying in Sydney, I worked as a tutor for Machine Learning Subject at UTS.
show_downloads: false
google_analytics: G-FS01M16PSB
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme # Enable remote themes
  - jekyll-feed         # RSS feed
  - jekyll-seo-tag      # SEO tags
  - jekyll-sitemap      # Sitemap generation

gem:
  - "github-pages"
  - group: :jekyll_plugins
