title: "Marisara Satrulee"
logo: "/assets/img/FaceProfile.png"
description: "I am a recent graduate of the Master of Data Science and Innovation program at the University of Technology Sydney (UTS), Australia. Prior to pursuing my master's degree, I had 10 years of experience in sales, marketing, and content creation for companies in the retail and education sectors. While studying, I tutored new students in Machine Learning at UTS."
show_downloads: false
google_analytics: G-FS01M16PSB
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme # Enable remote themes
  - jekyll-feed         # RSS feed
  - jekyll-seo-tag      # SEO tags
  - jekyll-sitemap      # Sitemap generation

gem:
  - "github-pages"
  - group: :jekyll_plugins
