title: Marisara Satrulee
logo: /assets/img/FaceProfile.png.png
description: Data Science Graduate with 10 years of experience in retail and eduction.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
