title: Marisara Satrulee
logo: /assets/img/FaceProfile.png
description: Data Science Graduate with 10 years of experience in retail and education.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
